/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

export const publicThemeSchema = z.union([
  z.literal("cyan"),
  z.literal("yellow"),
  z.literal("navy"),
  z.literal("green"),
  z.literal("purple"),
]);

export const publicBalanceRowSchema = z.object({
  created_at: z.string(),
  current: z.number(),
  expenses: z.number(),
  id: z.number(),
  income: z.number(),
  user_id: z.string(),
});

export const publicBalanceInsertSchema = z.object({
  created_at: z.string().optional(),
  current: z.number().optional(),
  expenses: z.number().optional(),
  id: z.number().optional(),
  income: z.number().optional(),
  user_id: z.string().optional(),
});

export const publicBalanceUpdateSchema = z.object({
  created_at: z.string().optional(),
  current: z.number().optional(),
  expenses: z.number().optional(),
  id: z.number().optional(),
  income: z.number().optional(),
  user_id: z.string().optional(),
});

export const publicBalanceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("balance_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicBudgetsRowSchema = z.object({
  category_id: z.number(),
  id: z.number(),
  maximum: z.number(),
  theme_id: z.number(),
  user_id: z.string(),
});

export const publicBudgetsInsertSchema = z.object({
  category_id: z.number(),
  id: z.number().optional(),
  maximum: z.number(),
  theme_id: z.number(),
  user_id: z.string().optional(),
});

export const publicBudgetsUpdateSchema = z.object({
  category_id: z.number().optional(),
  id: z.number().optional(),
  maximum: z.number().optional(),
  theme_id: z.number().optional(),
  user_id: z.string().optional(),
});

export const publicBudgetsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("budgets_category_id_fkey"),
    columns: z.tuple([z.literal("category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("budgets_theme_id_fkey"),
    columns: z.tuple([z.literal("theme_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("colors"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("budgets_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCategoriesRowSchema = z.object({
  created_at: z.string(),
  id: z.number(),
  label: z.string(),
  value: z.string(),
});

export const publicCategoriesInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  label: z.string().optional(),
  value: z.string().optional(),
});

export const publicCategoriesUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.number().optional(),
  label: z.string().optional(),
  value: z.string().optional(),
});

export const publicColorsRowSchema = z.object({
  created_at: z.string(),
  hex: z.string(),
  id: z.number(),
  label: z.string(),
  value: z.string(),
});

export const publicColorsInsertSchema = z.object({
  created_at: z.string().optional(),
  hex: z.string(),
  id: z.number().optional(),
  label: z.string(),
  value: z.string(),
});

export const publicColorsUpdateSchema = z.object({
  created_at: z.string().optional(),
  hex: z.string().optional(),
  id: z.number().optional(),
  label: z.string().optional(),
  value: z.string().optional(),
});

export const publicPotsRowSchema = z.object({
  id: z.number(),
  name: z.string(),
  target: z.number(),
  theme_id: z.number(),
  total: z.number(),
  user_id: z.string(),
});

export const publicPotsInsertSchema = z.object({
  id: z.number().optional(),
  name: z.string(),
  target: z.number(),
  theme_id: z.number(),
  total: z.number(),
  user_id: z.string().optional(),
});

export const publicPotsUpdateSchema = z.object({
  id: z.number().optional(),
  name: z.string().optional(),
  target: z.number().optional(),
  theme_id: z.number().optional(),
  total: z.number().optional(),
  user_id: z.string().optional(),
});

export const publicPotsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("pots_theme_id_fkey"),
    columns: z.tuple([z.literal("theme_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("colors"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("pots_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTransactionsRowSchema = z.object({
  amount: z.number(),
  avatar: z.string(),
  category_id: z.number(),
  date: z.string(),
  id: z.number(),
  name: z.string(),
  recurring: z.boolean(),
  user_id: z.string(),
});

export const publicTransactionsInsertSchema = z.object({
  amount: z.number(),
  avatar: z.string(),
  category_id: z.number(),
  date: z.string(),
  id: z.number().optional(),
  name: z.string(),
  recurring: z.boolean(),
  user_id: z.string().optional(),
});

export const publicTransactionsUpdateSchema = z.object({
  amount: z.number().optional(),
  avatar: z.string().optional(),
  category_id: z.number().optional(),
  date: z.string().optional(),
  id: z.number().optional(),
  name: z.string().optional(),
  recurring: z.boolean().optional(),
  user_id: z.string().optional(),
});

export const publicTransactionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("transactions_category_id_fkey"),
    columns: z.tuple([z.literal("category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transactions_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUsersRowSchema = z.object({
  created_at: z.string(),
  email: z.string(),
  id: z.string(),
  name: z.string(),
});

export const publicUsersInsertSchema = z.object({
  created_at: z.string().optional(),
  email: z.string(),
  id: z.string().optional(),
  name: z.string(),
});

export const publicUsersUpdateSchema = z.object({
  created_at: z.string().optional(),
  email: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
});

export type PublicTheme = z.infer<typeof publicThemeSchema>;
export type PublicBalanceRow = z.infer<typeof publicBalanceRowSchema>;
export type PublicBalanceInsert = z.infer<typeof publicBalanceInsertSchema>;
export type PublicBalanceUpdate = z.infer<typeof publicBalanceUpdateSchema>;
export type PublicBalanceRelationships = z.infer<
  typeof publicBalanceRelationshipsSchema
>;
export type PublicBudgetsRow = z.infer<typeof publicBudgetsRowSchema>;
export type PublicBudgetsInsert = z.infer<typeof publicBudgetsInsertSchema>;
export type PublicBudgetsUpdate = z.infer<typeof publicBudgetsUpdateSchema>;
export type PublicBudgetsRelationships = z.infer<
  typeof publicBudgetsRelationshipsSchema
>;
export type PublicCategoriesRow = z.infer<typeof publicCategoriesRowSchema>;
export type PublicCategoriesInsert = z.infer<
  typeof publicCategoriesInsertSchema
>;
export type PublicCategoriesUpdate = z.infer<
  typeof publicCategoriesUpdateSchema
>;
export type PublicColorsRow = z.infer<typeof publicColorsRowSchema>;
export type PublicColorsInsert = z.infer<typeof publicColorsInsertSchema>;
export type PublicColorsUpdate = z.infer<typeof publicColorsUpdateSchema>;
export type PublicPotsRow = z.infer<typeof publicPotsRowSchema>;
export type PublicPotsInsert = z.infer<typeof publicPotsInsertSchema>;
export type PublicPotsUpdate = z.infer<typeof publicPotsUpdateSchema>;
export type PublicPotsRelationships = z.infer<
  typeof publicPotsRelationshipsSchema
>;
export type PublicTransactionsRow = z.infer<typeof publicTransactionsRowSchema>;
export type PublicTransactionsInsert = z.infer<
  typeof publicTransactionsInsertSchema
>;
export type PublicTransactionsUpdate = z.infer<
  typeof publicTransactionsUpdateSchema
>;
export type PublicTransactionsRelationships = z.infer<
  typeof publicTransactionsRelationshipsSchema
>;
export type PublicUsersRow = z.infer<typeof publicUsersRowSchema>;
export type PublicUsersInsert = z.infer<typeof publicUsersInsertSchema>;
export type PublicUsersUpdate = z.infer<typeof publicUsersUpdateSchema>;
